### PR TITLE
Tidy-up to allow building without warnings or errors on Linux. 

### PR DESCRIPTION
**Pull request by iwbnwif**
Mostly these were a few remaining missing wxSOLID replacements and ensuring that all classes have virtual dtors where needed.

### CODE REVIEW

**Comment by PBfordev** [comment]
Thanks, I blindly merged the PR. The thing is, I found that wxFreeChart unfortunately does not have same features I required so after I cloned it to GitHub and made few changes, I pretty much abandoned it. Do you have any plans with wxFreeChart, considering its author does not maintain it anymore? Unfortunately, I do not have ability nor capacity to really improve wxFreeChart. 

Regarding the hash map, I did not get any warning when building wxChart with your PR merged with VS 2008. I of course agree with your remark about std:map; as I always say: such wxWidgets containers have no place outside the library itself.

**Comment by iwbnwif** [comment]
Thanks for your message. 

I am probably in a similar position to you in that I would love to spend more time on it but there are a lot of other things to do as well (not least is to sort out wxTreeListCtrl and wxShapeFramework!!).

> I found that wxFreeChart unfortunately does not have same features I required

Out of interest what do you end up using / doing? I have been round this loop more times than I care to admit. I keep coming back (sporadically!) to wxFreeChart because implements about 70% of what I want and has the right licence. With some TLC it could probably be quite good but if there is something else out there that I missed then maybe it's not worth it.

For reference, the improvements I would like to make (separately and for different projects) are as follows:
- Better axis labelling (see issues)
- Proper log grid lines
- Curve smoothing
- Shading under the graph
- Real time updates (bit like Windows TaskManager graphs)

> when building wxChart with your PR merged with VS 2008

I am building on Linux with gcc, so this probably explains the difference. I included a comment against the change that this may cause problems on Windows so it may need to be wrapped in a #define.

Anyway, if your version is abandoned then I won't send pull requests and create a new repository that is forked from wxCode instead. Please let me grab my issues though before you delete the project :)

**Comment by PBfordev** [comment]
> Out of interest what do you end up using / doing?

Unfortunately, I did not find anything better, it seems there is no good maintained wxWidgets charting component.  :(

The features I needed (for a simple XY plot) and wxFreeChart did not have:
- zooming and panning,
- it is supposed to support scrolling of the chart, but I couldn't get it work,
- does not support interactivity, i.e. no mouse or keyboard events (such as series or point clicked etc.), it seems there is some code for it but it was not implemented.

As I wrote before, I cannot really help, I'm not even a programmer. Perhaps what I could do is to at least create also a wxWidgets 3 MSVC 2015 project the same way I did with MSVC 2008 (so new potential users can try wxFreeChart easily) and test if it builds properly on MSW with your future changes. OTOH, it would be much better to create CMake project (as AFAIK bakefile does not support newer MS IDEs), but once again, this is beyond my ability.

**Comment by iwbnwif** [comment]
There is some overlap with the features we are looking for. 

I am only an amateur, but I would quite like to attempt to do some basic things. I don't know anything about cmake though.

**Pull request merged**
